name: Terraform Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Find Terraform Directories
        run: |
          find . -type f -name "*.tf" \
          | xargs -n1 dirname \
          | sort -u > terraform_dirs.txt

      - name: Validate Terraform
        run: |
          while read dir; do
            echo "Validating $dir"
            cd "$dir"

            terraform init -backend=false

            terraform validate

            cd - >/dev/null
          done < terraform_dirs.txt